#!/bin/bash


#izablog - an experimental blog platform in bash
#license: MIT
#full source code and license at http://github.com/izabera/izabera.github.io
#report bugs and feature requests to izabera


function printbar () {
  local value="$1"
  local total="$2"
  local i=0
  echo -n "["
  for (( ; i<10; i++ )); do
    if (( i >= (value*10)/total )); then
      echo -n "$(tput setab 1)"    #red
    else
      echo -n "$(tput setab 2)"    #green
    fi
    echo -n " "
  done
  echo -n "$(tput sgr0)]"
  echo -n " Progress: $value/$total"
  [ -n "$3" ] && echo -n " - $3"
  [[ "$1" != "$2" ]] && echo -en "\r" || echo
}


function disqussify () {
  if [[ "$disqusplugin" == "true" ]]; then
    cat > disqus <<EOF
<div class='container' id='disqus_thread'></div>
<script type='text/javascript'>
var disqus_shortname = '$disqus_name';
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href='http://disqus.com' class='dsq-brlink'>comments powered by <span class='logo-disqus'>Disqus</span></a>
EOF
  fi
}


function generateindex () {
  wordcount=0
  [[ "$rewrite_urls" == "true" ]] && newfile=${newfile%.html}
  {
    echo -n "<h1><a href='html/$newfile'>"
    head -n1 "$file" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
    echo "</a></h1>"
    [[ "$show_date_in_index" == "true" ]] && sed "s/XXX/$timestamp/" < "$basedir/blog/timestamp"
    if (( preview_words > 0 )); then
      echo "<p>"
      sed '1,2d' "$file" | while read line; do
        IFS=' '
        for word in $line ; do
          (( wordcount < preview_words )) && echo "$word"
          (( wordcount++ ))
        done
      done
      echo -n "<a href='html/$newfile'>(Read more)</a></p><hr>"
    fi
  } >> ../index
}


#prepare
basedir="$PWD"
log=$(date '+%s')
if [ -z "$1" ]; then
  message=$(date)
else 
  message="$*"
fi
mkdir -p logs
rm -rf temp old 2> "$basedir/logs/$log"
mkdir -p temp/listed temp/unlisted src/indexed src/notindexed
mv html old 2>> "$basedir/logs/$log"
mkdir html
cd blog
shopt -s extglob
rm -rf !(settings|defaults|timestamp)
source settings
cp defaults/head head
cp defaults/bottom bottom
sed -i "s/YYY/$title/" head
sed -i "s/XXX/$owner/" bottom
disqussify
cat disqus bottom > temp 2>> "$basedir/logs/$log"
mv temp bottom


#copy
cd ../src
cd indexed
numindexed=(*)
numindexed=${#numindexed[@]}
cd ../notindexed
numnotindexed=(*)
numnotindexed=${#numnotindexed[@]}
total=$(( numindexed + numnotindexed ))
[[ "$total" -eq 0 ]] && echo "Nothing to do" && exit
count=0
printbar "$count" "$total" "Copying files"
shopt -s nullglob
for file in *; do
  newfile=$(mktemp -u -p . "$(date '+%s' -r "$file")-XXXXXXXX")
  newfile=${newfile#./}
  cp "$file" "$basedir/temp/unlisted/$newfile"
  (( count++ ))
  printbar "$count" "$total" "Copying files"
done
cd ../indexed
for file in *; do
  newfile=$(mktemp -u -p . "$(date '+%s' -r "$file")-XXXXXXXX")
  newfile=${newfile#./}
  cp "$file" "$basedir/temp/listed/$newfile"
  echo "$newfile" >> "$basedir/temp/list"
  (( count++ ))
  printbar "$count" "$total" "Copying files"
done


#markdownify
cd "$basedir/temp"
count=0
printbar "$count" "$total" "Markdown conversion"
cd unlisted
for file in *; do
  title="$(head -n1 "$file")"
  newfile="$(echo "$title" | tr 'A-Z ' 'a-z-' | tr -dc '0-9a-z-').html"
  #assuming no edit has been made to the generated html files
  if grep "$(sha1sum "$file" | awk '{print $1}')" "$basedir/shasums" &> /dev/null  \
    && [[ -f "$basedir/old/$newfile" ]]; then
    cp "$basedir/old/$newfile" "$basedir/html/$newfile"
  else
    sha1sum "$file" | awk '{print $1}' >> "$basedir/shasums"
    timestamp="$(date "$dateformat" -d "@${file:0:10}")"
    sed "s/XXX/$title/" < "$basedir/blog/head" > "$basedir/html/$newfile"
    python -m markdown "$file" >> "$basedir/html/$newfile"
    [[ "$show_date_in_article" == "true" ]] &&  \
      sed "s/XXX/$timestamp/" < "$basedir/blog/timestamp" >> "$basedir/html/$newfile"
    echo "<a href='../../' id='back'>Back</a>" >> "$basedir/html/$newfile"
    cat "$basedir/blog/bottom" >> "$basedir/html/$newfile"
  fi
  (( count++ ))
  printbar "$count" "$total" "Markdown conversion"
done
cd ../listed
sort -r ../list | while read file ; do
  title="$(head -n1 "$file")"
  newfile="$(echo "$title" | tr 'A-Z ' 'a-z-' | tr -dc '0-9a-z-').html"
  timestamp="$(date "$dateformat" -d "@${file:0:10}")"
  if grep "$(sha1sum "$file" | awk '{print $1}')" "$basedir/shasums" &> /dev/null   \
     && [[ -f "$basedir/old/$newfile" ]]; then
    cp "$basedir/old/$newfile" "$basedir/html/$newfile"
  else
    sha1sum "$file" | awk '{print $1}' >> "$basedir/shasums"
    sed "s/XXX/$title/" < "$basedir/blog/head" > "$basedir/html/$newfile"
    python -m markdown "$file" >> "$basedir/html/$newfile"
    [[ "$show_date_in_article" == "true" ]] &&  \
      sed "s/XXX/$timestamp/" < "$basedir/blog/timestamp" >> "$basedir/html/$newfile"
    echo "<a href='../../' id='back'>Back</a>" >> "$basedir/html/$newfile"
    cat "$basedir/blog/bottom" >> "$basedir/html/$newfile"
  fi
  (( count++ ))
  printbar "$count" "$total" "Markdown conversion"
  generateindex
done


#create index and finish
cd "$basedir"
sed -i "s/XXX/index/" blog/head
cp blog/defaults/bottom blog/bottom
sed -i "s/XXX/$owner/" blog/bottom
cat blog/head temp/index blog/bottom > index.html
rm -rf temp old
[[ "$gitplugin" == "true" ]] &&  \
  git add -A &&  \
  git commit -m "$message" &&  \
  [[ "$gitpush" == "true" ]] &&  \
  git push


#done
echo
echo "$(tput bold)Done$(tput sgr0)"
echo "Log file saved in $basedir/logs/$log"

